server:
  port: 8083

spring:
  application:
    name: ms-matricula

  datasource:
    url: jdbc:postgresql://localhost:5432/ms_matricula
    username: postgres
    password: "123456"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost


feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 3000

management:
  server:
    base-path: /actuator
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ms-curso:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

  retry:
    instances:
      ms-curso:
        max-attempts: 2
        wait-duration: 500ms
